/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORTS_H_RPCGEN
#define _AIRPORTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STATE 3
#define MAX_CODE 4
#define MAX_NAME 65

typedef char codetypeA[MAX_CODE];

typedef char nametypeA[MAX_NAME];

typedef char statetypeA[MAX_STATE];

typedef struct airportA *airportListA;

struct lat_lon {
	double latitude;
	double longitude;
};
typedef struct lat_lon lat_lon;

struct airportA {
	codetypeA code;
	nametypeA name;
	statetypeA state;
	lat_lon location;
	double distance;
	airportListA next;
};
typedef struct airportA airportA;

struct airports_reply {
	int error;
	union {
		airportListA list;
	} airports_reply_u;
};
typedef struct airports_reply airports_reply;

#define AIRPORTS_SERVER_PROG 0x20807023
#define AIRPORTS_SERVER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define AIRPORTS_QUERY 1
extern  airports_reply * airports_query_1(lat_lon *, CLIENT *);
extern  airports_reply * airports_query_1_svc(lat_lon *, struct svc_req *);
extern int airports_server_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AIRPORTS_QUERY 1
extern  airports_reply * airports_query_1();
extern  airports_reply * airports_query_1_svc();
extern int airports_server_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_codetypeA (XDR *, codetypeA);
extern  bool_t xdr_nametypeA (XDR *, nametypeA);
extern  bool_t xdr_statetypeA (XDR *, statetypeA);
extern  bool_t xdr_airportListA (XDR *, airportListA*);
extern  bool_t xdr_lat_lon (XDR *, lat_lon*);
extern  bool_t xdr_airportA (XDR *, airportA*);
extern  bool_t xdr_airports_reply (XDR *, airports_reply*);

#else /* K&R C */
extern bool_t xdr_codetypeA ();
extern bool_t xdr_nametypeA ();
extern bool_t xdr_statetypeA ();
extern bool_t xdr_airportListA ();
extern bool_t xdr_lat_lon ();
extern bool_t xdr_airportA ();
extern bool_t xdr_airports_reply ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORTS_H_RPCGEN */
