/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "airports.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

airports_reply *
airports_query_1(lat_lon *argp, CLIENT *clnt)
{
	static airports_reply clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, AIRPORTS_QUERY,
		(xdrproc_t) xdr_lat_lon, (caddr_t) argp,
		(xdrproc_t) xdr_airports_reply, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
