
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = places_client
SERVER = places_server

CLIENTA = airports_client
SERVERA = airports_server
 
SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = places.x

SOURCESA_CLNT.c =
SOURCESA_CLNT.h =
SOURCESA_SVC.c =
SOURCESA_SVC.h =
SOURCESA.x = airports.x

TARGETS_SVC.c = places_svc.c places_server.c places_xdr.c airports_xdr.c airports_clnt.c Tries.c Linkedlist.c 
TARGETS_CLNT.c = places_clnt.c places_client.c places_xdr.c 
TARGETS = places.h airports.h places_xdr.c places_clnt.c places_svc.c places_client.c places_server.c

TARGETSA_SVC.c = airports_svc.c airports_server.c airports_xdr.c kdtree.c
TARGETSA_CLNT.c = airports_clnt.c airports_client.c airports_xdr.c
TARGETSA = airports.h airports_xdr.c airports_clnt.c airports_svc.c airports_client.c airports_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)

OBJECTSA_CLNT = $(SOURCESA_CLNT.c:%.c=%.o) $(TARGETSA_CLNT.c:%.c=%.o)
OBJECTSA_SVC = $(SOURCESA_SVC.c:%.c=%.o) -lm $(TARGETSA_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl
RPCGENFLAGS = 

# Targets 

all : $(CLIENT) $(SERVER) $(SERVERA)

#$(TARGETS) : $(SOURCES.x) 
#	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c)
 
$(OBJECTSA_CLNT) : $(SOURCESA_CLNT.c) $(SOURCESA_CLNT.h) $(TARGETSA_CLNT.c)

$(OBJECTSA_SVC) : $(SOURCESA_SVC.c) $(SOURCESA_SVC.h) $(TARGETSA_SVC.c)

$(CLIENT) : $(OBJECTS_CLNT)
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS)  

$(CLIENTA) : $(OBJECTSA_CLNT)
	$(LINK.c) -o $(CLIENTA) $(OBJECTSA_CLNT) $(LDLIBS)

$(SERVER) : $(OBJECTS_SVC)
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)  

$(SERVERA) : $(OBJECTSA_SVC) 
	$(LINK.c) -o $(SERVERA) $(OBJECTSA_SVC) $(LDLIBS)

Tries.o : Tries.c
	$(LINK.c) -c -o Tries.o Tries.c

kdtree.o : kdtree.c
	$(LINK.c) -c -o kdtree.o kdtree.c

clean:
	$(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER) $(TARGETSA) $(OBJECTSA_CLNT) $(OBJECTSA_SVC) $(CLIENTA) $(SERVERA)

