/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"


void
places_server_prog_1(char *host, char* city, char* state)
{
	CLIENT *clnt;
	places_reply  *result_1;
	city_state  places_query_1_arg;
	airportList list;

#ifndef	DEBUG
	clnt = clnt_create (host, PLACES_SERVER_PROG, PLACES_SERVER_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	strcpy(places_query_1_arg.name, city);
	strcpy(places_query_1_arg.state, state);
	result_1 = places_query_1(&places_query_1_arg, clnt);
	if (result_1 == (places_reply *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}
	if (result_1->error == -1) {
                perror("\nNo city is found!\n");
		printf("\n");
		exit(1);
        } else if (result_1->error == 1) {
                perror("\nYour input is so ambiguity! Please refine the query.\n");
		printf("\n");
		exit(1);
        } else {
                printf("\n%s, %s: %f, %f \n", result_1->places_reply_u.list.city.name,
                        result_1->places_reply_u.list.city.state,
                        result_1->places_reply_u.list.city.lat,
                        result_1->places_reply_u.list.city.lon);
                for (list = result_1->places_reply_u.list.airports; list != NULL; list = list->next) {
                        printf("code=%s, name=%s, state=%s distance: %.2f miles\n", list->code, list->name,
                                list->state, list->distance); 
                }
		printf("\n");
        }
#ifndef	DEBUG
	clnt_freeres(clnt, (xdrproc_t)xdr_places_reply, (char *)&result_1);
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *city;
        char *state;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	city = argv[2];
        state = argv[3];
	places_server_prog_1 (host, city, state);
exit (0);
}
