/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STATE 3
#define MAX_CODE 4
#define MAX_NAME 65

typedef char codetype[MAX_CODE];

typedef char nametype[MAX_NAME];

typedef char statetype[MAX_STATE];

typedef struct airport *airportList;

struct place {
	nametype name;
	statetype state;
	double lat;
	double lon;
};
typedef struct place place;

struct city_state {
	nametype name;
	statetype state;
};
typedef struct city_state city_state;

struct airport {
	codetype code;
	nametype name;
	statetype state;
	double lat;
	double lon;
	double distance;
	airportList next;
};
typedef struct airport airport;

struct place_airports {
	place city;
	airportList airports;
};
typedef struct place_airports place_airports;

struct places_reply {
	int error;
	union {
		place_airports list;
	} places_reply_u;
};
typedef struct places_reply places_reply;

#define PLACES_SERVER_PROG 0x20902687
#define PLACES_SERVER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PLACES_QUERY 1
extern  places_reply * places_query_1(city_state *, CLIENT *);
extern  places_reply * places_query_1_svc(city_state *, struct svc_req *);
extern int places_server_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PLACES_QUERY 1
extern  places_reply * places_query_1();
extern  places_reply * places_query_1_svc();
extern int places_server_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_codetype (XDR *, codetype);
extern  bool_t xdr_nametype (XDR *, nametype);
extern  bool_t xdr_statetype (XDR *, statetype);
extern  bool_t xdr_airportList (XDR *, airportList*);
extern  bool_t xdr_place (XDR *, place*);
extern  bool_t xdr_city_state (XDR *, city_state*);
extern  bool_t xdr_airport (XDR *, airport*);
extern  bool_t xdr_place_airports (XDR *, place_airports*);
extern  bool_t xdr_places_reply (XDR *, places_reply*);

#else /* K&R C */
extern bool_t xdr_codetype ();
extern bool_t xdr_nametype ();
extern bool_t xdr_statetype ();
extern bool_t xdr_airportList ();
extern bool_t xdr_place ();
extern bool_t xdr_city_state ();
extern bool_t xdr_airport ();
extern bool_t xdr_place_airports ();
extern bool_t xdr_places_reply ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
